#!/usr/bin/perl

$file1 = $ARGV[0];
$file2 = $ARGV[1];
$count = $ARGV[2];

if ($count == 0)
{
    $count = 8;
    print "Comparing the first 8 characters of $file1 $file2 \n";
}

#print "$ARGV[0] $ARGV[1] $ARGV[2]";

$out1 = "tmp1";
$out2 = "tmp2";

#print $out1;
#print $out2;

open(IN, $file1);
open(OUT, ">$out1");
while (<IN>)
{
   $s = substr($_, 0, $count);
   print OUT "$s\n";
}
close(IN);
close(OUT);
   
open(IN, $file2);
open(OUT, ">$out2");
while (<IN>)
{
   $s = substr($_, 0, $count);
   print OUT "$s\n";
}
close(IN);
close(OUT);

system "/usr/bin/diff -i $out1 $out2";
#system "rm -f $out1 $out2";



